name: AI API

on:
  push:
    paths:
      - 'ai-api/**'

jobs:  
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-api/requirements.txt
          pip install flake8  # Ensure Flake8 is installed

      - name: Run Flake8
        run: flake8 --max-line-length=180 .

      - name: Test
        env: 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          PYTHONPATH=./ai-api python -m unittest discover -s "ai-api/test" -p "test_*.py"
