name: AI API

on:
  push:
    branches:
      - main
    paths:
      - 'ai-api/**'
      - '.github/workflows/ai-api.yml'
  pull_request:
    paths:
      - 'ai-api/**'
      - '.github/workflows/ai-api.yml'

env:
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  TEST_AC_TOKEN: ${{ secrets.TEST_AC_TOKEN }}

permissions:
  contents: read
  pull-requests: write  

concurrency:
  group: ai-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.6'
      
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-api/requirements.txt
          pip install flake8 tabulate

      - name: Run Code Linter (Flake8)
        run: flake8 --max-line-length=180 .

      - name: Run Unit Tests
        run: |
          PYTHONPATH=./ai-api python -m unittest discover -s "ai-api/test/unit_tests" -p "test_*.py"

      - name: Run Integration Tests
        run: |
          PYTHONPATH=./ai-api python -m unittest discover -s "ai-api/test/integration" -p "test_*.py"

      - name: Run Performance Tests
        run: |
          if [ -f "ai-api/test/performance/performance_test.py" ]; then
            PYTHONPATH=./ai-api python ai-api/test/performance/performance_test.py
          else
            echo "Performance test file not found, skipping..."
          fi
      
      - name: Post Performance Results as PR Comment
        if: github.event_name == 'pull_request' && success()
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ai-api/test/performance/performance_report.md
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wrk
        run: |
          sudo apt update
          sudo apt install -y wrk

      - name: Start Flask App
        run: |
          nohup python ai-api/run_app.py
          sleep 10

      - name: Wait for API to start
        run: sleep 5  # Adjust if needed

      - name: Run Load Tests
        id: benchmark
        run: |
          URL="http://127.0.0.1:5000/instagram_webhook"

          # Define different test cases
          TEST1=$(wrk -t2 -c10 -d10s $URL)
          TEST2=$(wrk -t4 -c20 -d10s $URL)
          
          # Format results
          echo "### Load Test Results" > wrk_results.md
          echo "#### **Test 1**: 2 threads, 10 connections, 10s" >> wrk_results.md
          echo '```' >> wrk_results.md
          echo "$TEST1" >> wrk_results.md
          echo '```' >> wrk_results.md
          
          echo "#### **Test 2**: 4 threads, 20 connections, 10s" >> wrk_results.md
          echo '```' >> wrk_results.md
          echo "$TEST2" >> wrk_results.md
          echo '```' >> wrk_results.md

      - name: Comment on PR with Benchmark Results
        if: github.event_name == 'pull_request' && success()
        uses: mshick/add-pr-comment@v2
        with:
          message-path: wrk_results.md
          repo-token: ${{ secrets.GITHUB_TOKEN }}