name: AI API

on:
  push:
    paths:
      - 'ai-api/**'
      - '.github/workflows/ai-api.yml'

jobs:  
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 8
    concurrency:
      group: ai-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.6'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-api/requirements.txt
          pip install flake8  # Ensure Flake8 is installed

      - name: Run Flake8
        run: flake8 --max-line-length=180 .

      - name: Test
        env: 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          PYTHONPATH=./ai-api python -m unittest discover -s "ai-api/test" -p "test_*.py"
