name: Branch Pipeline

on:
  push:
    branches-ignore:
      - main

permissions:
  packages: read
  contents: read  # Allow reading the repository contents
  actions: read   # Allow actions to run
  security-events: write  # Allow uploading security events

jobs:
  python:
    name: Python Clean Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # Ensure Flake8 is installed

      - name: Run Flake8
        run: flake8 .
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Here should be the commands to build

      - name: Test
        run: |
          # Here should be the commands to test
