name: Code Analysis

on:
  push:
    branches:
      - main

jobs:
  count-lines:
    name: Count Lines of Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install cloc
      - name: Install cloc
        run: sudo apt-get install -y cloc

      # Step 3: Count lines of code
      - name: Count lines of code
        id: cloc
        run: |
          cloc . --json --report-file=cloc_report.json
          cat cloc_report.json

      # Step 4: Output the total lines of code
      - name: Parse total lines
        id: parse-total
        run: |
          total_lines=$(jq '.SUM.code' cloc_report.json)
          echo "Total lines of code: $total_lines"
          echo "::set-output name=total_lines::$total_lines"

      # Step 5: Print the result or use it in further steps
      - name: Display total lines
        run: echo "The repository has ${{ steps.parse-total.outputs.total_lines }} lines of code!"
