name: Deploy

on:
  workflow_run:
    workflows: ["Default Pipeline"]  # Name of the first workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}  # Check if the triggering workflow was from the main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying..."
