name: Secret Scanner

on: [push]

jobs:
  scan-secrets:
    name: Scan Secrets
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history.
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Run Gitleaks using the official action.
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: ""      # Use default config or specify a custom file.
          fail: false          # Continue to the next detector even if secrets are found.

      # Step 3: Install TruffleHog.
      - name: Install TruffleHog
        run: |
          wget https://github.com/trufflesecurity/trufflehog/releases/download/v3.14.0/trufflehog_3.14.0_linux_amd64.tar.gz
          tar -xzf trufflehog_3.14.0_linux_amd64.tar.gz
          sudo mv trufflehog /usr/local/bin/

      # Step 4: Run TruffleHog and process its JSON output with jq.
      - name: Run TruffleHog and Filter JSON Output
        run: |
          # Run the scanner; output is one JSON object per line.
          trufflehog --no-update filesystem --directory="${{ github.workspace }}" --json | \
          # For each JSON line, extract key fields.
          jq -r '{commit: .SourceMetadata.Data.Git.commit, file: .SourceMetadata.Data.Git.file, detector: .DetectorName, secret: .Raw}' > trufflehog_filtered.json
          echo "Filtered TruffleHog results:"
          cat trufflehog_filtered.json

      # Step 5: Upload the filtered TruffleHog results as an artifact.
      - name: Upload TruffleHog Output
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-scan-results
          path: trufflehog_filtered.json
