name: Secret Scanner

on: [push]

jobs:
  scan-secrets:
    name: Scan Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available for scanning

      # Run Gitleaks Detector
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: ""  # Use a custom config file if needed
          fail: false      # Do not fail immediately to allow the next detector to run

      # Run TruffleHog Detector
      - name: Run TruffleHog
        uses: edplato/trufflehog-actions-scan@main
        continue-on-error: true  # Continue even if TruffleHog finds secrets
        with:
          repo_path: "."
          base: "HEAD~50"         # Scans the last 50 commits
