name: Gitleaks Secret Scanner

on: [push]

permissions:
  contents: read

jobs:
  gitleaks_scan:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to scan all commits

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --verbose