name: Twister

on:
  push:
    paths:
      - 'twister/**'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./twister/gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Linting
        run: ./gradlew ktlintCheck
        working-directory: ./twister

      - name: Run tests
        run: ./gradlew test
        working-directory: ./twister

      - name: Compile project
        run: ./gradlew build
        working-directory: ./twister
