name: Build and Test Web API

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'web-api/**'
      - '.github/workflows/web-api.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: web-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build web-api/web-api --configuration Release

      - name: Run linting
        run: dotnet format web-api/web-api/web-api.csproj --verify-no-changes

      - name: Test
        run: dotnet test web-api/web-api/web-api.csproj --no-build --verbosity normal
