name: WEB API

on:
  push:
    paths:
      - 'web-api/**'
      - '.github/workflows/web-api.yml'

jobs:  
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: web-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Build
        run: |
          dotnet build web-api/web-api

      - name: Restore dependencies
        run: dotnet restore web-api/web-api.csproj

      - name: Run linting
        run: |
          dotnet format web-api/web-api/web-api.csproj --verify-no-changes

      - name: Test
        run: dotnet test web-api/web-api/web-api.csproj --no-build --verbosity normal
